name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPO_URI }}:latest .

      - name: Run Unit Tests
        run: |
          ./mvnw test

      - name: Run Integration Tests
        run: |
          ./mvnw verify

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REPO_URI }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Update ECS service
        run: |
          aws ecs update-service --cluster casestudy-cluster --service casestudy-service --force-new-deployment

  test:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Install Newman (Postman CLI)
        run: |
          npm install -g newman

      - name: Run Postman tests
        run: |
          newman run path/to/your/collection.json -e path/to/your/environment.json

